CREATE CACHED TABLE "PUBLIC"."HVAC_EQUIPMENTS"(
    "UUID" UUID NOT NULL,
    "CREATED_AT" TIMESTAMP NOT NULL,
    "DELETED_AT" TIMESTAMP,
    "ORIGIN_REFERENCE" VARCHAR(255),
    "UPDATED_AT" TIMESTAMP NOT NULL,
    "VERSION" BIGINT NOT NULL,
    "NAME" VARCHAR(255),
    "SEASON" INTEGER,
    "MINIMUM_IDLE_MINUTES" INTEGER,
    "MINIMUM_EXECUTION_MINUTES" INTEGER
);
ALTER TABLE "PUBLIC"."HVAC_EQUIPMENTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_10" PRIMARY KEY("UUID");
