CREATE CACHED TABLE "PUBLIC"."HVAC_EQUIPMENTS"(
    "UUID" UUID NOT NULL,
    "CREATED_AT" TIMESTAMP NOT NULL,
    "DELETED_AT" TIMESTAMP,
    "ORIGIN_REFERENCE" VARCHAR(255),
    "UPDATED_AT" TIMESTAMP NOT NULL,
    "VERSION" BIGINT NOT NULL,
    "NAME" VARCHAR(255),
    "SEASON" INTEGER,
    "MINIMUM_IDLE_MINUTES" INTEGER,
    "MINIMUM_EXECUTION_MINUTES" INTEGER
);
ALTER TABLE "PUBLIC"."HVAC_EQUIPMENTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_10" PRIMARY KEY("UUID");

ALTER TABLE "PUBLIC"."HOME_INFO" ADD "HVAC_SUMMER_POWER_METER_ID" VARCHAR(255);
ALTER TABLE "PUBLIC"."HOME_INFO" ADD "HVAC_WINTER_POWER_METER_ID" VARCHAR(255);
ALTER TABLE "PUBLIC"."HOME_INFO" ADD "OPTIMIZER_MODE" INTEGER;
ALTER TABLE "PUBLIC"."HOME_INFO" ADD "HVAC_SWITCH_ENTITY_ID" VARCHAR(255);
ALTER TABLE "PUBLIC"."HOME_INFO" ADD "CURRENT_WINTER_HVAC_EQUIPMENT_UUID" UUID;
ALTER TABLE "PUBLIC"."HOME_INFO" ADD "CURRENT_SUMMER_HVAC_EQUIPMENT_UUID" UUID;
ALTER TABLE "PUBLIC"."HOME_INFO" ADD CONSTRAINT "PUBLIC"."FKJY7PS9PF1PS80UMDFFYAF7GC5" FOREIGN KEY("CURRENT_WINTER_HVAC_EQUIPMENT_UUID") REFERENCES "PUBLIC"."HVAC_EQUIPMENTS"("UUID") NOCHECK;
ALTER TABLE "PUBLIC"."HOME_INFO" ADD CONSTRAINT "PUBLIC"."FKJY7PS9PF1PS80UMDFFYAF7GC6" FOREIGN KEY("CURRENT_SUMMER_HVAC_EQUIPMENT_UUID") REFERENCES "PUBLIC"."HVAC_EQUIPMENTS"("UUID") NOCHECK;
